//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escritor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escritor()
        {
            this.LibroEscritor = new HashSet<LibroEscritor>();
        }
    
        public int id_escritor { get; set; }
        public string nombre_escritor { get; set; }
        public string nacionalidad_escritor { get; set; }
        public int activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroEscritor> LibroEscritor { get; set; }
    }
}
