//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroEscritor
    {
        public int id_libroescritor { get; set; }
        public int id_libro { get; set; }
        public int id_escritor { get; set; }
    
        public virtual Escritor Escritor { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
