//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.PrestamoLibro = new HashSet<PrestamoLibro>();
        }
    
        public int id_usuario { get; set; }
        public string nombres_usuario { get; set; }
        public string apellidos_usuario { get; set; }
        public int edad { get; set; }
        public string direccion_usuario { get; set; }
        public int id_tipoUsuario { get; set; }
        public int activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestamoLibro> PrestamoLibro { get; set; }
        public virtual tipoUsuario tipoUsuario { get; set; }
    }
}
